server:
  port: 8081

spring:
  datasource: # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/eatmeat?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: root
  redis:
    database: 1
    password: xiaotian
    host: 101.43.107.106
    port: 6379


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl